# Generated by Django 6.0.3 on 2026-04-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='series',
            field=models.ManyToManyField(blank=True, related_name='blog_pages', to='blog.photoseriespage'),
        ),
    ]
