# Generated by Django 6.0.3 on 2026-04-24 13:12

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpage_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='series',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='blog_pages', to='blog.photoseriespage'),
        ),
    ]
