# Generated by Django 6.0.3 on 2026-07-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_single_target_page_for_pinned_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="photoseriespage",
            name="map_style",
            field=models.CharField(
                choices=[
                    ("openstreetmap", "OpenStreetMap"),
                    ("contours", "Contours"),
                ],
                default="openstreetmap",
                help_text="Choose the visual treatment for this series map.",
                max_length=32,
            ),
        ),
    ]
