# Generated by Django 6.0.3 on 2026-07-31

from django.db import migrations, models


def set_existing_series_to_contours(apps, schema_editor):
    PhotoSeriesPage = apps.get_model("blog", "PhotoSeriesPage")
    PhotoSeriesPage.objects.filter(map_style="openstreetmap").update(map_style="contours")


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_photoseriespage_map_style"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photoseriespage",
            name="map_style",
            field=models.CharField(
                choices=[
                    ("openstreetmap", "OpenStreetMap"),
                    ("contours", "Contours"),
                ],
                default="contours",
                help_text="Choose the visual treatment for this series map.",
                max_length=32,
            ),
        ),
        migrations.RunPython(set_existing_series_to_contours, migrations.RunPython.noop),
    ]
