# Generated by Django 6.0.3 on 2026-04-02 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropboxConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Optional name for this connection', max_length=255)),
                ('account_id', models.CharField(help_text='Dropbox account ID', max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, help_text='Optional email associated with the account', max_length=254)),
                ('access_token', models.CharField(help_text='Dropbox access token', max_length=255)),
                ('refresh_token', models.CharField(blank=True, help_text='Dropbox refresh token (optional)', max_length=255, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='When the access token expires', null=True)),
                ('root_folder', models.CharField(default='/30_Kýrauga/00_web_importer/to_publish', help_text='Root folder to import from', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this connection is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportedDropboxAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dropbox_file_id', models.CharField(help_text='Dropbox file ID', max_length=255)),
                ('dropbox_path_lower', models.CharField(help_text='Lowercase Dropbox path', max_length=500)),
                ('dropbox_path_display', models.CharField(help_text='Display Dropbox path', max_length=500)),
                ('dropbox_content_hash', models.CharField(help_text='Dropbox content hash', max_length=255)),
                ('dropbox_rev', models.CharField(help_text='Dropbox revision', max_length=255)),
                ('server_modified', models.DateTimeField(blank=True, help_text='When the file was last modified on Dropbox', null=True)),
                ('file_size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('status', models.CharField(choices=[('imported', 'Imported'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='imported', help_text='Import status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the import')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(help_text='The Dropbox connection this asset was imported from', on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='media_importer.dropboxconnection')),
                ('wagtail_image', models.ForeignKey(blank=True, help_text='The corresponding Wagtail image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropbox_import_records', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['-imported_at'],
                'constraints': [models.UniqueConstraint(fields=('connection', 'dropbox_file_id'), name='unique_connection_file_id')],
            },
        ),
    ]
