# Generated by Django 6.0.3 on 2026-04-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_importer', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='importeddropboxasset',
            name='unique_connection_file_id',
        ),
        migrations.AlterField(
            model_name='importeddropboxasset',
            name='dropbox_file_id',
            field=models.CharField(help_text='Dropbox file ID', max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name='importeddropboxasset',
            constraint=models.UniqueConstraint(fields=('dropbox_file_id',), name='unique_dropbox_file_id'),
        ),
        migrations.RemoveField(
            model_name='importeddropboxasset',
            name='connection',
        ),
        migrations.DeleteModel(
            name='DropboxConnection',
        ),
    ]
