# Generated by Django 6.0.3 on 2026-04-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_importer', '0002_remove_importeddropboxasset_unique_connection_file_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropboxAuthState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.TextField(blank=True)),
                ('connected_account_id', models.CharField(blank=True, max_length=255)),
                ('connected_email', models.EmailField(blank=True, max_length=254)),
                ('connected_name', models.CharField(blank=True, max_length=255)),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
