# Generated by Django 6.0.3 on 2026-04-09 20:23

import django.db.models.deletion
import modelsearch.index
import taggit.managers
import wagtail.images.models
import wagtail.models.media
from django.conf import settings
from django.db import migrations, models


def copy_existing_wagtail_images(apps, schema_editor):
    from media_importer.services.importer import build_icelandic_description, extract_photo_metadata

    DefaultImage = apps.get_model("wagtailimages", "Image")
    CustomImage = apps.get_model("media_importer", "CustomImage")
    ContentType = apps.get_model("contenttypes", "ContentType")
    TaggedItem = apps.get_model("taggit", "TaggedItem")

    for old_image in DefaultImage.objects.all():
        if CustomImage.objects.filter(pk=old_image.pk).exists():
            continue

        custom_image = CustomImage(
            id=old_image.id,
            title=old_image.title,
            file=old_image.file,
            description=old_image.description,
            width=old_image.width,
            height=old_image.height,
            created_at=old_image.created_at,
            focal_point_x=old_image.focal_point_x,
            focal_point_y=old_image.focal_point_y,
            focal_point_width=old_image.focal_point_width,
            focal_point_height=old_image.focal_point_height,
            uploaded_by_user_id=old_image.uploaded_by_user_id,
            file_size=old_image.file_size,
            collection_id=old_image.collection_id,
            file_hash=old_image.file_hash,
        )

        metadata = {}
        try:
            with old_image.file.open("rb") as image_file:
                metadata = extract_photo_metadata(image_file.read())
        except Exception:
            metadata = {}

        gps = metadata.get("gps") or {}
        custom_image.taken_at = metadata.get("taken_at")
        custom_image.camera_make = metadata.get("camera_make", "")
        custom_image.camera_model = metadata.get("camera_model", "")
        custom_image.lens_model = metadata.get("lens_model", "")
        custom_image.focal_length_mm = metadata.get("focal_length_mm")
        custom_image.shutter_speed = metadata.get("shutter_speed", "")
        custom_image.aperture = metadata.get("aperture")
        custom_image.iso = metadata.get("iso")
        custom_image.gps_latitude = gps.get("latitude")
        custom_image.gps_longitude = gps.get("longitude")
        custom_image.location_name = metadata.get("location_name", "")
        custom_image.location_city = metadata.get("location_city", "")
        custom_image.location_country = metadata.get("location_country", "")

        if not custom_image.description:
            custom_image.description = build_icelandic_description(metadata)

        custom_image.save(force_insert=True)

    old_content_type = ContentType.objects.get(app_label="wagtailimages", model="image")
    new_content_type, _ = ContentType.objects.get_or_create(
        app_label="media_importer",
        model="customimage",
    )

    for tagged_item in TaggedItem.objects.filter(content_type=old_content_type):
        TaggedItem.objects.get_or_create(
            tag_id=tagged_item.tag_id,
            content_type_id=new_content_type.id,
            object_id=tagged_item.object_id,
        )


def reverse_copy_existing_wagtail_images(apps, schema_editor):
    CustomImage = apps.get_model("media_importer", "CustomImage")
    CustomImage.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('media_importer', '0003_dropboxauthstate'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('file', wagtail.images.models.WagtailImageField(height_field='height', upload_to=wagtail.images.models.get_upload_to, verbose_name='file', width_field='width')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='description')),
                ('width', models.IntegerField(editable=False, verbose_name='width')),
                ('height', models.IntegerField(editable=False, verbose_name='height')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('focal_point_x', models.PositiveIntegerField(blank=True, null=True)),
                ('focal_point_y', models.PositiveIntegerField(blank=True, null=True)),
                ('focal_point_width', models.PositiveIntegerField(blank=True, null=True)),
                ('focal_point_height', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(editable=False, null=True)),
                ('file_hash', models.CharField(blank=True, db_index=True, editable=False, max_length=40)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('camera_make', models.CharField(blank=True, max_length=255)),
                ('camera_model', models.CharField(blank=True, max_length=255)),
                ('lens_model', models.CharField(blank=True, max_length=255)),
                ('focal_length_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('shutter_speed', models.CharField(blank=True, max_length=64)),
                ('aperture', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('iso', models.PositiveIntegerField(blank=True, null=True)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('location_city', models.CharField(blank=True, max_length=255)),
                ('location_country', models.CharField(blank=True, max_length=255)),
                ('collection', models.ForeignKey(default=wagtail.models.media.get_root_collection_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.collection', verbose_name='collection')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text=None, through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags')),
                ('uploaded_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='uploaded by user')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.images.models.ImageFileMixin, modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='CustomRendition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_spec', models.CharField(db_index=True, max_length=255)),
                ('file', wagtail.images.models.WagtailImageField(height_field='height', storage=wagtail.images.models.get_rendition_storage, upload_to=wagtail.images.models.get_rendition_upload_to, width_field='width')),
                ('width', models.IntegerField(editable=False)),
                ('height', models.IntegerField(editable=False)),
                ('focal_point_key', models.CharField(blank=True, default='', editable=False, max_length=16)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renditions', to='media_importer.customimage')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('image', 'filter_spec', 'focal_point_key'), name='unique_rendition')],
            },
            bases=(wagtail.images.models.ImageFileMixin, models.Model),
        ),
        migrations.RunPython(copy_existing_wagtail_images, reverse_copy_existing_wagtail_images),
        migrations.AlterField(
            model_name='importeddropboxasset',
            name='wagtail_image',
            field=models.ForeignKey(blank=True, help_text='The corresponding Wagtail image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropbox_import_records', to='media_importer.customimage'),
        ),
    ]
